### ISSUE TITLE
Can you use fast render with template level subscriptions?

### ISSUE THREAD

**Issue by gazhayes** [abecks/meteor-fast-render#11]
The documentation is not very clear. A lot of people have been asking on the Meteor forums but no one has any answers: can you use fast render without using route level subscriptions? How exactly? Thanks!

**Comment by abecks** [comment]
You can by using FlowRouter.route on the server

**Comment by abecks** [comment]
I mean FastRender.route also FastRender.onAllRoutes

**Comment by gazhayes** [comment]
Ah I see, thanks! Got it working.
