### ISSUE TITLE
Replace meteorhacks:fast-render with staringatlights:fast-render

### ISSUE THREAD

**Issue by Silverutm** [abecks/meteor-fast-render#22]
I'm using a package (ryw:blog) that uses meteorhacks:fast-render as a dependecy

Is there a way to replace it with staringatlights:fast-render?

It seems meteorhacks:fast-render is broken and not working properly with newer versions of meteor.

**Comment by abecks** [comment]
You should make a pull request to that package to change the dependency. If
that isn't an option, you can install this package locally and rename it to
meteorhacks:fast-render in Package.js
