### ISSUE TITLE
[Meteor 1.9] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by DenisGorbachev** [abecks/meteor-fast-render#33]
I'm getting `DeprecationWarning: OutgoingMessage.prototype._headers is deprecated` after updating to Meteor 1.9. Most probably, this can be fixed by using `setHeader` / `getHeaders` instead of `_headers`. Could you please push this small fix?

**Comment by stolinski** [comment]
would love it if anyone could merge this please.

**Comment by chris-visser** [comment]
I've just created a fork with this fix and am currently adding it as dep in the vue-ssr package - which I'm currently maintaining
