### ISSUE TITLE
dynamics.slice is not a function

### ISSUE THREAD

**Issue by dnish** [abecks/meteor-fast-render#4]
Since Meteor 1.5.1 I get the following error message:

```
W20170803-23:40:59.076(2)? (STDERR) error on fast-rendering path: /de/search/drake ; error: TypeError: dynamics.slice is not a function
W20170803-23:40:59.076(2)? (STDERR)     at Object.Meteor.bindEnvironment (packages/meteor.js:1166:41)
W20170803-23:40:59.076(2)? (STDERR)     at PublishContext._.extend.onStop (packages/ddp-server/livedata_server.js:1226:23)
W20170803-23:40:59.077(2)? (STDERR)     at Context.processPublication (packages/staringatlights_fast-render.js:497:18)
W20170803-23:40:59.077(2)? (STDERR)     at packages/staringatlights_fast-render.js:313:15
W20170803-23:40:59.077(2)? (STDERR)     at Array.forEach (native)
W20170803-23:40:59.077(2)? (STDERR)     at Context.<anonymous> (packages/staringatlights_fast-render.js:310:18)
W20170803-23:40:59.078(2)? (STDERR)     at packages/staringatlights_fast-render.js:285:18
W20170803-23:40:59.078(2)? (STDERR)     at Array.forEach (native)
W20170803-23:40:59.078(2)? (STDERR)     at packages/staringatlights_fast-render.js:284:31

```

Any idea what's going on?

**Comment by jaredtmartin** [comment]
I'm getting the same thing
`error on fast-rendering path: /donations ; error: TypeError: dynamics.slice is not a function
W20170803-16:22:55.075(-6)? (STDERR)     at Object.Meteor.bindEnvironment (packages/meteor.js:1166:41)
W20170803-16:22:55.076(-6)? (STDERR)     at PublishContext._.extend.onStop (packages/ddp-server/livedata_server.js:1226:23)
W20170803-16:22:55.078(-6)? (STDERR)     at Context.processPublication (packages/staringatlights_fast-render.js:497:18)
W20170803-16:22:55.079(-6)? (STDERR)     at packages/staringatlights_fast-render.js:313:15
W20170803-16:22:55.081(-6)? (STDERR)     at Array.forEach (native)
W20170803-16:22:55.081(-6)? (STDERR)     at Context.<anonymous> (packages/staringatlights_fast-render.js:310:18)
W20170803-16:22:55.082(-6)? (STDERR)     at packages/staringatlights_fast-render.js:285:18
W20170803-16:22:55.083(-6)? (STDERR)     at Array.forEach (native)
W20170803-16:22:55.084(-6)? (STDERR)     at packages/staringatlights_fast-render.js:284:31
`

**Comment by FinnFrotscher** [comment]
+1

**Comment by bensventures** [comment]
I'm also having this issue. Is anyone using some related package like FlowRouter, or Meteor DocHead? I've been staring at the code for a few hours and can't find where this is coming from...

**Comment by jaredtmartin** [comment]
I’m using Flow Router with this package.

**Comment by bensventures** [comment]
The problem disappears if you downgrade the `meteor` package in `.meteor/versions` from `1.7.1` to `1.7.0`.

I am guessing the issue we're seeing might be related to the removal of the underscore.js dependency and the related refactor (see https://github.com/meteor/meteor/commit/7f062192e1f9e4cb669d378b1140da9a33b0db42)

So maybe this is a Meteor issue and not this package's problem.

**Comment by hexsprite** [comment]
Wondering if this is related to the changes in DDP from Meteor's `History.md`:
> this.onStop callbacks in publications are now run with the publication's context and with its EnvironmentVariables bound. PR #8629

**Comment by Vandell63** [comment]
+1

**Comment by lobosan** [comment]
Hi, I just upgraded my app from 1.4.4.3 to 1.5.2 and I'm seeing this error in the console
`error on fast-rendering path: / ; error: TypeError: dynamics.slice is not a function`

**Comment by abecks** [comment]
What version of Fast Render are you using?

**Comment by lobosan** [comment]
@abecks in my .meteor/versions I see meteorhacks:fast-render@2.16.0

**Comment by abecks** [comment]
The `meteorhacks` version of Fast Render is no longer supported. You need to switch to `staringatlights:fast-render`. If you are using Flow Router, you may also need to switch to `staringatlights:flow-router`.

**Comment by lobosan** [comment]
Yes I'm using flow-router, is there any change that I have to make in my code or I just have to switch packages?

**Comment by abecks** [comment]
Just switch packages

**Comment by lobosan** [comment]
Thanks I'll give it a try

**Comment by lobosan** [comment]
Just in case this is the content of my versions file. Should I change another package?
```
abpetkov:switchery@0.1.0
accounts-base@1.3.2
accounts-password@1.4.0
alanning:roles@1.2.16
aldeed:autoform@5.8.1
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
aldeed:tabular@1.6.1
allow-deny@1.0.6
amplify@1.0.0
audit-argument-checks@1.0.7
autoupdate@1.3.12
awsp:handsontable@0.16.1
babel-compiler@6.20.0
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-tools@1.0.10
boilerplate-generator@1.2.0
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
chrismbeckett:toastr@2.1.2_1
chuangbo:cookie@1.1.0
coffeescript@1.12.7_1
coffeescript-compiler@1.12.7_1
ddp@1.3.0
ddp-client@2.1.0
ddp-common@1.2.9
ddp-rate-limiter@1.0.7
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
digilord:faker@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.2
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ejson@1.0.14
email@1.2.3
flowkey:numeric@1.0.3
fortawesome:fontawesome@4.7.0
fourseven:scss@3.13.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
kevohagan:sweetalert@1.0.0
livedata@1.0.18
localstorage@1.1.1
logging@1.1.17
maazalik:highcharts@0.4.0
mdg:validation-error@0.5.1
meteor@1.7.1
meteor-base@1.1.0
meteorhacks:fast-render@2.16.0
meteorhacks:inject-data@2.0.0
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
meteorhacks:ssr@2.2.0
meteortoys:toykit@3.0.4
minifier-css@1.2.16
minifier-js@2.1.3
minimongo@1.3.0
modules@0.10.0
modules-runtime@0.8.0
momentjs:moment@2.18.1
mongo@1.2.0
mongo-dev-server@1.0.1
mongo-id@1.0.6
msavin:mongol@2.0.1
npm-bcrypt@0.9.3
npm-mongo@2.2.30
observe-sequence@1.0.16
ongoworks:security@2.1.0
ordered-dict@1.0.9
promise@0.9.0
raix:eventemitter@0.1.3
raix:handlebar-helpers@0.2.5
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
sacha:spin@2.3.1
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.4
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
stevezhu:lodash@4.17.2
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
themeteorchef:bert@2.1.1
themeteorchef:jquery-validation@1.14.0
tracker@1.1.3
twbs:bootstrap@3.3.6
u2622:persistent-session@0.4.4
ui@1.0.13
underscore@1.0.10
url@1.1.0
webapp@1.3.18
webapp-hashing@1.0.9
```

**Comment by abecks** [comment]
You may run into issues where other packages depend on `kadira:flow-router` but there isn't any other option right now. Give it a shot and if other packages still depend on flow-router, ask them to add it as a soft dependency (with mine) instead.

**Comment by lobosan** [comment]
I see, what about `meteorhacks:inject-data` ?

**Comment by abecks** [comment]
You'll want my version instead, `staringatlights:inject-data`

**Comment by nicooprat** [comment]
Had this issue after updating to Meteor 1.5.2, and can confirm it works well after switching to `staringatlights:fast-render`, `staringatlights:flow-router` and `staringatlights:inject-data`. Thanks!

**Comment by lobosan** [comment]
So far it seems to be working fine for me, but I cannot say that is a 100% free of bugs just yet

**Comment by noahsw** [comment]
@abecks I'm a little confused. https://atmospherejs.com/staringatlights/flow-router says it was updated in December 2016. The git repo shows no changes in years. How is this different than kadira:flow-router?

**Comment by abecks** [comment]
The only difference is that it uses my Fast Render package instead of Kadira's, which no longer works.

**Comment by hexsprite** [comment]
might be a good idea to put some message at the top of the README

**Comment by igeto** [comment]
@abecks Does it need code refactoring or just changing the packages is enough?

**Comment by igeto** [comment]
@abecks omg sorry I just read that my question was already asked AND answered 
but, anyway, if there r any new changes up until now, I'd appreciate a reply
