### ISSUE TITLE
Doesn't work with FlowRouter

### ISSUE THREAD

**Issue by anubhav756** [abecks/meteor-fast-render#6]
```
FlowRouter.route('/', {
  name: 'Main',
  subscriptions() {
    this.register('allTeams', Meteor.subscribe('allTeams'));
  },
  action() {
    mount(Basic, { content: <App /> });
  },
});
```

This doesn't work. But this does:

```
if (Meteor.isServer) {
  FastRender.route('/', function () {
    this.subscribe('allTeams');
  });
}

FlowRouter.route('/', {
  name: 'Main',
  action() {
    mount(Basic, { content: <App /> });
  },
});
```

Meteor: `1.5.1`
Versions:
```
accounts-base@1.3.1
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.6
autoupdate@1.3.12
babel-compiler@6.19.4
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.1.1
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
chuangbo:cookie@1.1.0
ddp@1.3.0
ddp-client@2.0.0
ddp-common@1.2.9
ddp-rate-limiter@1.0.7
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.2
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ejson@1.0.13
es5-shim@4.6.15
fastclick@1.0.13
fourseven:scss@3.10.1
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
jquery@1.11.10
kadira:flow-router@2.12.1
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.1.1
logging@1.1.17
materialize:materialize@0.99.0
mdg:validation-error@0.2.0
meteor@1.7.0
meteor-base@1.1.0
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
minifier-css@1.2.16
minifier-js@2.1.1
minimongo@1.2.1
mobile-experience@1.0.4
mobile-status-bar@1.0.14
modules@0.9.2
modules-runtime@0.8.0
mongo@1.1.19
mongo-id@1.0.6
npm-mongo@2.2.24
observe-sequence@1.0.16
ordered-dict@1.0.9
promise@0.8.9
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.8
react-meteor-data@0.2.12
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
shell-server@0.2.4
spacebars@1.0.15
spacebars-compiler@1.1.2
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
staringatlights:fast-render@2.16.4
staringatlights:inject-data@2.0.5
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.2.0
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
webapp@1.3.17
webapp-hashing@1.0.9
```

**Comment by abecks** [comment]
Try using staringatlights:flow-router

**Comment by dhamaniasad** [comment]
@abecks What's the difference with `kadira:flow-router`?

**Comment by abecks** [comment]
Kadira's version has been abandoned and is no longer updated. I'm
maintaining my version to work with my fork of Fast Render. There are also
other versions of flow router being maintained if you want to shop around.

**Comment by dhamaniasad** [comment]
@abecks I used it like this:

```javascript
loggedIn = FlowRouter.group({
    subscriptions: function (params, queryParams) {
        if (Meteor.isServer) {
            this.register("test", Meteor.subscribe("test"));
        }
    }
});
```

Along with the `staringatlights:flow-router` package, but it only seems to send over some data about the user in the HTML, and no data from the subscription I actually subscribe to ends up in the HTML.

**Comment by abecks** [comment]
Curious why you are using Meteor.isServer in the route like that?

If the route is defined on both the client and the server, all you need to
do is add `fastrender: true`, to the route definition:

```
const iContactDefaults = _.extend({}, defaults, {
  subscriptions (params, queryParams) {
    this.register('Newsletters', Meteor.subscribe('Newsletters'))
  },
  fastRender: true
})
```

Alternatively, you can specify the route manually on the server using
`FastRender.route`

**Comment by dhamaniasad** [comment]
I should add `fastRender: true` when using FlowRouter as well? 

I did do that, and removed the `Meteor.isServer`. This is the only data I get in the html still:

```html
<script type="text/inject-data">{"fast-render-data":{"collectionData":{"users":[[{"username":"REDACTED","emails":[{"address":"REDACTED","verified":true}],"_id":"REDACTED"}]],"AnalyticsUsers":[[{"services":{},"emails":[{"address":"REDACTED","verified":true}],"_id":"REDACTED"}]]},"subscriptions":{},"loginToken":"REDACTED"}}</script>
```

**Comment by abecks** [comment]
Can you provide a minimal reproduction? By the way, groups don't really
work properly in Flow Router, never have. You'll notice my technique is to
extend from a defaults object versus using the group.

**Comment by dhamaniasad** [comment]
@abecks I'll try a few workarounds, and if it still doesn't work I'll try to make a reproduction. Can you  expand a little on the defaults object technique? I use groups throughout my app to bundle the routes together, so that'll be a lot to change.

**Comment by abecks** [comment]
Sure,

I started out trying to use groups too, and still have them in my code:
```
const adminRoutes = FlowRouter.group({  ... })
```

But I found that not all of the properties of the group are inherited for
each route (I can't remember which). There a bug report for it in the
kadira flow router repo somewhere. To workaround the issue, I make a
defaults object:
```
const defaults = {
  layout: 'Layouts_main',
  action: RouteAction
}
```

Then extend it for each route:
```
// Company Index
adminRoutes.route('/admin/clients', _.extend({}, defaults, {
  name: 'companyIndex',
  layout: 'Layouts_main_flush',
  template: 'Companies_index_page',
  title: 'Clients'
}))
```

I should also note subscriptions are not inherited if you define some in a
group and then some in a specific route, and I end up having to do things
like:

```
function companySubscriptions (params, queryParam) {
    this.register('Company', Meteor.subscribe('Company', params.companyId))
    this.register('CompanyQuizzes', Meteor.subscribe('CompanyQuizzes',
params.companyId))
    this.register('CompanyUsers', Meteor.subscribe('CompanyUsers',
params.companyId))
    this.register('ChildCompanies', Meteor.subscribe('ChildCompanies',
params.companyId))
}

companyRoutes.route('/companies/:companyId/users/new', _.extend({},
companyDefaults, {
  name: 'companyUsersCreate',
  template: 'Companies_users_new_page',
  title: 'Add User',
  subscriptions (params, queryParams) {
    companyDefaults.subscriptions.call(this, params, queryParams)
    this.register('Newsletters', Meteor.subscribe('Newsletters',
params.companyId))
  }
}))
```

**Comment by dhamaniasad** [comment]
Thanks for the writeup @abecks! I'll try your approach. I also noticed you have packages for `active-route` and `flow-router-helpers`, but they do not seem to be compatible with `staringatlights:flow-router`. 

If I define the subscriptions on the group, it does not work. It works if I define it on individual routes, so I guess your object extension approach will be the best bet.

**Comment by abecks** [comment]
I'm using local builds of those packages, which I probably have unreleased
bug fixes for. I'll take a look at that later.

**Comment by dhamaniasad** [comment]
Guess I'll have to go the local route as well then, since this package does not work with `kadira:flow-router`. But your object extend approach worked for me, thanks so much for all the help! 😄

**Comment by anubhav756** [comment]
`staringatlights:flow-router` works! Thanks for the quick fix @abecks. You can close the issue :+1:

**Comment by abecks** [comment]
Cheers!
